//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Common.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ModeratorId { get; set; }
        public System.DateTime DateBanned { get; set; }
        public int DaysBanned { get; set; }
    
        public virtual Moderator Moderator { get; set; }
        public virtual User User { get; set; }
    }
}
