//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Common.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Posts_hashtags = new HashSet<Posts_hashtags>();
        }
    
        public int Id { get; set; }
        public string Post1 { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> DayPosted { get; set; }
        public string Topic { get; set; }
        public int AutorId { get; set; }
    
        public virtual PostCategory PostCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts_hashtags> Posts_hashtags { get; set; }
    }
}
